services:
  postgres-order:
    image: postgres:16
    container_name: ap4-postgres-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - ./order-service/migrations:/docker-entrypoint-initdb.d
      - order_data:/var/lib/postgresql/data

  postgres-payment:
    image: postgres:16
    container_name: ap4-postgres-payment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5434:5432"
    volumes:
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
      - payment_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ap4-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: ap4-redis
    ports:
      - "6379:6379"

  payment-service:
    build: ./payment-service
    container_name: ap4-payment-service
    environment:
      PAYMENT_DB_URL: postgres://postgres:postgres@postgres-payment:5432/payments_db?sslmode=disable
      PAYMENT_GRPC_PORT: 50052
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres-payment
      - rabbitmq

  order-service:
    build: ./order-service
    container_name: ap4-order-service
    environment:
      ORDER_DB_URL: postgres://postgres:postgres@postgres-order:5432/orders_db?sslmode=disable
      ORDER_HTTP_PORT: 8080
      ORDER_GRPC_PORT: 50051
      PAYMENT_GRPC_ADDR: payment-service:50052
      REDIS_ADDR: redis:6379
      CACHE_TTL: 5m
      RATE_LIMIT: 10
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - postgres-order
      - payment-service
      - redis

  notification-service:
    build: ./notification-service
    container_name: ap4-notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDR: redis:6379
      PROVIDER_MODE: SIMULATED
      PROVIDER_LATENCY: 2s
      MAX_RETRIES: 3
    depends_on:
      - rabbitmq
      - redis

volumes:
  order_data:
  payment_data:
